### ISSUE TITLE
Globus transfer error

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#194] opened 2019-07-16 02:03 UTC
Hi @monaw I'm getting a globus transfer error: 

I'm not sure if this is related to what you were doing, but now I cannot upload data into the gateway. On the globus side I cam getting permissions denied errors: 

Error (make directories)
Endpoint: XSEDE Comet (de463f97-6d04-11e5-ba46-22000b92c6ec)
Server: oasis-dm.sdsc.xsede.org:2811
File: /projects/cosmic2/gateway/globus_transfers/mcianfro%40umich.edu/test/Mics/job002/micrograph_files/14sep05c_c_00003gr_00015sq_00006hl_00005es_c.mrcs
Command: MKD /projects/cosmic2/gateway/globus_transfers/mcianfro@umich.edu/test
Message: Fatal FTP response
---
Details: 550-GlobusError: v=1 c=PERMISSION_DENIED\r\n550-GridFTP-Errno: 13\r\n550-GridFTP-Reason: System error in mkdir\r\n550-GridFTP-Error-String: Permission denied\r\n550 End.\r\n

**Comment by monaw** [comment] 2019-07-18 18:49
d*mn, this is the same permission issue:

> drwxr-x--- 2 cosmic2-gw cosmic2    0 Jul 17 13:08 046f34e64f8b7dc1015072dc7aa30a1a@ucsd.edu/
> drwxr-x--- 2 cosmic2-gw cosmic2    0 Jul 15 07:07 iabhinit@iu.edu/
> drwxr-x--- 2 cosmic2-gw cosmic2    0 Jul 15 06:17 mackwill@umich.edu/
> drwxr-x--- 2 cosmic2-gw cosmic2    0 Jul  7 11:06 mcianfro@umich.edu/
> drwxrwx--- 4 cosmic2-gw cosmic2 1024 Jul 18 11:43 mona@xsede.org/
> 

Why is my directory created with the right permission and the others not?!   more debugging...

**Comment by monaw** [comment] 2019-07-19 17:14
GitHub issue #185

**Comment by monaw** [comment] 2019-07-19 17:15
Duplicate of #185

**Comment by monaw** [comment] 2019-10-10 19:29
I noticed that new users (on production) had no group write permission in their globus directory again.  I did a test and I got the same problem:

`drwxr-x---  2 cosmic2-gw cosmic2    0 Oct 10 10:45 046f34cb4b90efb0014d919e5f1b4ed9@ucsd.edu/`

So I uncommented some debug statements and then it worked:

`drwxrwx---  2 cosmic2-gw cosmic2    0 Oct 10 11:08 046f34cb4b90efb0014d919e5f1b4ed9@ucsd.edu/`

then I comment out the debug statement and it still worked.  so i don't know what the problem was...sigh...let's see what  happens with the next new user account setup...

**Comment by monaw** [comment] 2020-01-29 19:00
this problem appears to be fixed in production:

drwxrwx---  4 cosmic2-gw cosmic2  1024 Jan 23 12:27 baec2@nih.gov/

**Closed by monaw** 2020-01-29 19:00 UTC
Labels: bug
