### ISSUE TITLE
Set computing allocation limits per user

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#54] opened 2017-10-22 02:23 UTC
Set cap for users

**Comment by mcianfrocco** [comment] 2017-10-22 02:38
600 K80 SUs per user = 150 GPU-node hours = 6 x 24 hr jobs

**Comment by mcianfrocco** [comment] 2017-11-09 02:10
And, I would like to have the ability, in the future, to increase the usage of an individual user (e.g. after they apply for more time).

**Comment by mcianfrocco** [comment] 2017-11-09 02:12
One more thing - I want to be able to 'turn off' submissions, as in trying to fix a bug and I don't want users submitting jobs

**Comment by monaw** [comment] 2018-01-03 22:43
@mcianfrocco - What do you mean by "after they apply for more time" above?  Does the user apply to COSMIC2 or have their own allocation on a resource or something else?

**Comment by mcianfrocco** [comment] 2018-01-04 00:32
Hi @monaw - I decided that I would have my own allocation system within COSMIC2 for users to get extra time (if needed). While not a way to get a lot more time, I'll reserve time in case users need extra while they wait for an allocation from XSEDE

**Comment by monaw** [comment] 2018-01-04 00:41
ak ok.
fyi, i'm testing disabling a resource so if you see an issue...it might be due to that...or not...feel free to let me know...

**Comment by monaw** [comment] 2018-01-19 00:54
From Mark Miller:

> Our max runtime is 7 days, so we put in a reservation on Comet 7 days before any planned outage to hold cipres jobs that would be killed. That is an alternative way to handle this, but it isn’t as explicit for users, so they may not know why their jobs aren’t running. 
> 
> Adding to halt submissions for all users is possible but will create a problem as well.
> 
> There is a column for "canSubmit" populated by 0 or 1.
> You could run the script userCanSubmit wildcard false and turn off all submissions.
> But the problem will come when you want to turn them back on.
> We disable submissions from people who reach their limit with this mechanism.
> So you would have to have to have a way of leaving disabled the user accounts who were disabled.
> Or create an analogous column for global turnoffs, I guess. 
> 
> In the existing system, [there is a mechanism to]  Turn off all the compute resources. 
> In both cases, the jobs are not queued, they are saved in the user interface, but must be submitted again by the user (by machine turnoff) or cloned and resubmitted by the user (account disabled). So a new mechanism would be required to stop submission after the job is queued. Kenneth or Paul could say whether that is even possible. I think that would require a reservation on the system, something that involves the scheduler, not CIPRES software. Maybe Mahidhar could speak to how easy it is to put a reservation in. I suspect that he or someone in his group has to do that.

I did a test of the mechanism of halting all jobs but it seems the job is still being submitted.

@mcianfrocco - is there a log or something on Comet that I can view to see if a task submitted from the gateway actually ran?

**Comment by mcianfrocco** [comment] 2018-01-19 01:00
Hi @monaw - 

When we run jobs through the gateway, there are the stdout and stderr files that are created - would that work for you? They are found in the user's workspace as stdout.txt and stderr.txt. 

Mike

**Comment by monaw** [comment] 2018-02-01 21:06
Hi @mcianfrocco - ok, disabling job submission to Comet has been enabled.  The user will see this message on their task page when they try to submit their task:

![screen shot 2018-02-01 at 1 00 01 pm](https://user-images.githubusercontent.com/18472048/35703160-0df9fc10-0750-11e8-9dd0-9731759d772b.png)

This is accomplished by the file /projects/cosmic2/gateway/disabled_resources/COMET and the message can be customized by edit this file.  You can also set start and end dates.  So right now job submission is disabled; try it and see the behavior.    You can rename the file to something else to re-enable job submission.

Is this good enough for now or would you still like the ability to set compute limit per user?  FYI, this is not a CIPRES feature and will require some work.

**Comment by mcianfrocco** [comment] 2018-02-02 00:32
I just tried to rename / edit the file and I am getting permissions issues since you created it. Could you remove it and then create it as the root account?

**Comment by monaw** [comment] 2018-02-02 00:45
i don't have access to root account but i did just changed permission so cosmic2 group can edit it.  you should have permission now.

**Comment by monaw** [comment] 2018-02-02 00:46
yes, userCanSubmit script should still work.

checking on the cpu usage in db...

**Comment by mcianfrocco** [comment] 2018-02-02 00:50
Thanks for permissions change - works for me !

**Comment by monaw** [comment] 2018-02-02 16:25
great!  the nice thing about this mechanism is that it can be done live...don't require bringing the server down (:

**Comment by mcianfrocco** [comment] 2018-02-02 18:46
Great ! Also did you see the CPU usage in the database ?

**Comment by monaw** [comment] 2018-02-02 20:48
yes, working on it right now (:

**Comment by monaw** [comment] 2018-02-02 22:21
@mcianfrocco - the computation charge account is hvd125?  Is this information stored in the backend script?  If yes, where?

**Comment by monaw** [comment] 2018-02-02 23:13
documentation on disabled_resource/ mechanism is at https://svn.sdsc.edu/repo/scigap/trunk/documents/disabled_resources.txt

**Comment by mcianfrocco** [comment] 2018-02-03 00:45
Yes - that is it

**Comment by monaw** [comment] 2018-02-03 05:11
tech note: job_stats table tg_charge_number, su_charged, su_override, appname columns are null or empty!

**Comment by monaw** [comment] 2018-02-13 23:13
the remaining issue is to fix the user CPU usage display which is duplicate of issue #70 so let's close this one and move conversation to issue #70

**Comment by mcianfrocco** [comment] 2018-11-29 21:07
@kenneth59715 - could you put user job submission limit check into your chron job?

**Comment by mcianfrocco** [comment] 2019-03-16 23:36
@monaw - can I restart this thread - right now, the plan is to limit users manually through administrators turning off users? Or is this automatic?

**Comment by monaw** [comment] 2019-03-18 18:10
yes i believe to stop user from job submission requires admin to run the script to turn off the user and is not automatic

**Comment by kenneth59715** [comment] 2019-03-20 21:30
According to Tony and Mark, there are ways to have the gateway enforce usage limits on users.
Tony says the properties file can specify these limits:
xsede_us_su_limit=5000
xsede_nonus_su_limit=3000
other_us_su_limit=3000
other_nonus_su_limit=2000

Mark says the usageLimits script will also let us control this.

**Comment by kenneth59715** [comment] 2019-05-02 16:33
Our portal code base does not support these limits.  The plan is to migrate to
at least portal-R41.14.  his will also require database changes:
"Did you update all the components used to enforce those limits, not just UsageLimit.java?   There are two database changes, 08-13-2018.sql and 10-15-2018.sql."

Or should we try to get the old limits working?

**Comment by mcianfrocco** [comment] 2019-05-02 16:42
hi @kenneth59715 - do you think short term we just write a monitoring script check user usage and then turn off their submission while we wait to migrate the portal?

**Comment by kenneth59715** [comment] 2019-05-02 17:02
I think that should be possible.  I'll do that this week.

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment] 2019-05-02 19:03
I installed a script in cron to disable users who have used too much (3000) SU:
53 11 * * 1,2,3,4,5 /projects/cosmic2/gateway/scripts/disableonusage.py >/dev/null 2>&1
There is a list of users it will ignore, currently mona@xsede.org and mcianfro@umich.edu

**Comment by mcianfrocco** [comment] 2019-05-02 19:42
Great! How often does this check?

**Comment by kenneth59715** [comment] 2019-05-02 19:53
Mon-Fri once a day 11:13am.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment] 2019-05-03 02:54
Great - is there any way it can happen more often than that? Just trying to be conservative in our ability to protect against users submitting too many jobs before we catch it.

**Comment by kenneth59715** [comment] 2019-05-03 05:54
Sure, let me know what frequency is good.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment] 2019-05-03 12:30
Oh, but the usage data only gets updated overnight and the next day,
so it won't do any good to run the check more often.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kenneth59715** [comment] 2019-07-05 21:54
Yes, usageLimits in 41.14 allows per user control:
usageLimits -u <username> -x <new XSEDE SU limit>
list limits for a user:
usageLimits -u <username> -l

**Closed** 2019-07-31 20:20 UTC
Labels: enhancement
